linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - dupl
      # disabled dupl as we do have a lot of duplicated code between resources and their tests, which gets flagged by this
    - errcheck
      # errocheck disabled to silience errors here: https://travis-ci.com/nutanix/terraform-provider-nutanix/jobs/131154435
      # Example error:
        # nutanix/data_source_nutanix_image.go:61:7: Error return value of `d.Set` is not checked (errcheck)
        # d.Set("name", utils.StringValue(resp.Status.Name))
      # waiting on terraform/hashi to let us know how they want us to changle thoseerrors seeError return value of `d.Set` is not checked (errcheck)
