---
language: go
go:
  - 1.9.x
  - 1.10.x
  - master

go_import_path: github.com/terraform-providers/terraform-provider-nutanix

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - make deps

# install:
#   - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:$GOPATH"
#   - make cibuild

# before_script:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build

# script:
#   - make citest

# after_script:
#   - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT