---
language: go

cache:
  directories:
    - vendor
    - /home/travis/gopath/pkg

git:
  depth: 1

go_import_path: github.com/terraform-providers/terraform-provider-nutanix

script:
  - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:$GOPATH"
  - make cibuild

stages:
  - sanity testing
  - build go 1.9
  - build go 1.10
  - build go master
  - acceptance testing
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: sanity testing
      script:
        - make deps
        - make extrasanity
      go: 1.10.x
    # Build Go 1.9.x
    - stage: build go 1.9
      go: 1.9.x
      script:
        - make cibuild
      env: GOOS=darwin GOARCH=amd64
    - script:
        - make cibuild
      go: 1.9.x
      env: GOOS=windows GOARCH=amd64
    - script:
        - make cibuild
      go: 1.9.x
      env: GOOS=linux GOARCH=amd64
    - script:
        - make cibuild
      go: 1.9.x
      env: GOOS=linux GOARCH=ppc64
    # Build Go 1.10.x
    - stage: build go 1.9
      go: 1.10.x
      script:
        - make cibuild
      env: GOOS=darwin GOARCH=amd64
    - script:
        - make cibuild
      go: 1.10.x
      env: GOOS=windows GOARCH=amd64
    - script:
        - make cibuild
      go: 1.10.x
      env: GOOS=linux GOARCH=amd64
    - script:
        - make cibuild
      go: 1.10.x
      env: GOOS=linux GOARCH=ppc64
    # Build Go master (helps hedge against upstream code breaking downstream builds later, acts as a canary)
    - stage: build go master
      go: tip
      script:
        - make cibuild
      env: GOOS=darwin GOARCH=amd64
    - script:
        - make cibuild
      go: tip
      env: GOOS=windows GOARCH=amd64
    - script:
        - make cibuild
      go: tip
      env: GOOS=linux GOARCH=amd64
    - script:
        - make cibuild
      go: tip
      env: GOOS=linux GOARCH=ppc64
    - stage: acceptance testing
      go: 1.10.x
      script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - make citest
        - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
    - stage: deploy
      provider: script
      skip_cleanup: true
      script: curl -sL https://git.io/goreleaser | bash
      on:
        tags: true
        condition: $TRAVIS_GO_VERSION =~ ^99\.99\.

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
